### ISSUE TITLE
0.13.15-2022.2 - still not working with Intellij 2022.3

### ISSUE THREAD

**Issue by lemon4github** [MCMicS/jenkins-control-plugin#413]
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 12,4,main] 127561699
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1131194491
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1042)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1025)
	at com.intellij.ui.SpeedSearchBase.isPopupActive(SpeedSearchBase.java:180)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:63)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:52)
	at com.intellij.ui.speedSearch.SpeedSearchUtil.applySpeedSearchHighlightingFiltered(SpeedSearchUtil.java:185)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:124)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:53)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:179)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:553)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:723)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4407)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:616)
	at java.desktop/javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:320)
	at java.desktop/javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:227)
	at org.codinjutsu.tools.jenkins.JenkinsTree.clear(JenkinsTree.java:149)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.clearView(BrowserPanel.java:313)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.setJobsUnavailable(BrowserPanel.java:308)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.handleEmptyConfiguration(BrowserPanel.java:304)
	at org.codinjutsu.tools.jenkins.logic.BrowserPanelAuthenticationHandler.loginCancelled(BrowserPanelAuthenticationHandler.java:42)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:652)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:621)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:395)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:374)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:433)
	at jdk.proxy19/jdk.proxy19.$Proxy229.loginCancelled(Unknown Source)
	at org.codinjutsu.tools.jenkins.logic.LoginService$1.run(LoginService.java:45)
	at org.codinjutsu.tools.jenkins.logic.JenkinsBackgroundTask.run(JenkinsBackgroundTask.java:41)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MCMicS** [comment]
I will look at this again

Thanks for report

**Comment by MCMicS** [comment]
I can reproduce it if the job configuratiuon is wrong or the euthentication fails.

I will fix it

**Comment by MCMicS** [comment]
Please load following eap: I test it today a while and release it in stable channel too

https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/261229

**Comment by lemon4github** [comment]
Sadly it is still not working. Test connection needs extremly long and writes the message [Fail] URL malformed. It logs in the idea.log WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen. And dumps the thread:

AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.base@17.0.5/sun.nio.ch.Net.poll(Native Method)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base@17.0.5/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base@17.0.5/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:485)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:410)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.codinjutsu.tools.jenkins.security.DefaultSecurityClient.executeHttp(DefaultSecurityClient.java:216)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.doAuthentication(BasicSecurityClient.java:61)
	at org.codinjutsu.tools.jenkins.security.BasicSecurityClient.connect(BasicSecurityClient.java:48)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.testAuthenticate(RequestManager.java:320)
	at org.codinjutsu.tools.jenkins.view.ConfigurationPanel.testConnection(ConfigurationPanel.java:170)
	at org.codinjutsu.tools.jenkins.view.ConfigurationPanel.lambda$new$0(ConfigurationPanel.java:143)
	at org.codinjutsu.tools.jenkins.view.ConfigurationPanel$$Lambda$13444/0x00000008046911c8.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.ide.IdeEventQueue$$Lambda$688/0x000000080075fd28.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.ide.IdeEventQueue$$Lambda$687/0x000000080075fae0.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue$$Lambda$684/0x000000080073fc48.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:743)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1676)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1634)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:134)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:107)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:99)
	at org.codinjutsu.tools.jenkins.view.action.OpenPluginSettingsAction.showSettingsFor(OpenPluginSettingsAction.java:47)
	at org.codinjutsu.tools.jenkins.view.action.OpenPluginSettingsAction$$Lambda$13066/0x0000000804690268.accept(Unknown Source)
	at java.base@17.0.5/java.util.Optional.ifPresent(Optional.java:178)
	at org.codinjutsu.tools.jenkins.view.action.OpenPluginSettingsAction.actionPerformed(OpenPluginSettingsAction.java:43)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:195)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton$$Lambda$13037/0x0000000804677c48.run(Unknown Source)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:174)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:462)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.5/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.ide.IdeEventQueue$$Lambda$688/0x000000080075fd28.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.ide.IdeEventQueue$$Lambda$687/0x000000080075fae0.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue$$Lambda$684/0x000000080073fc48.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by MCMicS** [comment]
It looks like a different issue but I will check this later.

if it says that your URL is malformed.
can you post your Url?
You can also send me private messages in Gitter.

**Comment by lemon4github** [comment]
Sadly it is our internal server so that you can not test against it. The URL looks like
https://jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com/
and we use API-Token and Crumb Data with Jenkins version 2.x

**Comment by MCMicS** [comment]
I try to reproduce it

**Comment by MCMicS** [comment]
I'm not to reproduce it.
COuld you please test it with curl and send my ther result?
Maybe a server related issue (long timeout for example)

```
curl -v -u user:token https://jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com/api/json?tree=nodeName,url,description,primaryView%5Bname%2Curl%5D
```

**Comment by lemon4github** [comment]
With the curl our server responed directly with no timeout like in the Idea. Here you could see the log ...

*   Trying xx.xx.xxx.x:443...
* Connected to jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com (xx.xx.xxx.x) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server did not agree on a protocol. Uses default.
* Server auth using Basic with user '....'
> GET /api/json?tree=nodeName,url,description,primaryView%5Bname%2Curl%5D HTTP/1.1
> Host: jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com
> Authorization: Basic ...
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Tue, 06 Dec 2022 09:19:21 GMT
< x-content-type-options: nosniff
< x-jenkins: 2.332.2
< x-jenkins-session: 543e9882
< x-frame-options: deny
< content-type: application/json;charset=utf-8
< content-length: 260
< server: Jetty(9.4.43.v20210629)
< set-cookie: ...; path=/; HttpOnly; Secure; SameSite=None
< cache-control: private
<
{"_class":"hudson.model.Hudson","nodeName":"","description":null,"primaryView":{"_class":"hudson.model.AllView","name":"all","url":"https://jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com/"},"url":"https://jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com/"}* Connection #0 to host jenkins-xxx-xxx-dev.apps.xy01.ddd.x-internal.com left intact

**Comment by lemon4github** [comment]
By the way the latest plugin versions are also not working in my 2022.2.x Idea.
But I found a strange solution:
If I use the old in 2022.2 working version  0.13.14-2022.2 also in 2022.3 I'll get an java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpConnectionManager exception. When I then manually add the commons-httpclient-3.1.jar to the plugins lib folder it works also in 2022.3.
That means from the 0.13.14 version only the commons-httpclient jar is missing. 
0.13.15 does not work at all. Not in 2022.2 and also not in 2022.3.

**Comment by MCMicS** [comment]
The httpclient was removed from plugin because it should delivered from idea

Thanks for your logs i will investigate it

In my setups (at home and at work) it works with the 0.13.15 versions.
but i will look more at this

Thanks for 2022.2.x versions hint. I test it aganist with this version the day

**Comment by MCMicS** [comment]
But it sounds weired because the plugin loads the url and within parsing it response it seems to fail
i need time to investigate

**Comment by MCMicS** [comment]
> If I use the old in 2022.2 working version 0.13.14-2022.2 also in 2022.3 I'll get an java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpConnectionManager exception. When I then manually add the commons-httpclient-3.1.jar to the plugins lib folder it works also in 2022.3.

This is because I switched from older httclient to newer one which is included within idea libraries.
I would assists you ti find the problem why it not works in your environment

> 
```
Sadly it is still not working. Test connection needs extremly long and writes the message [Fail] URL malformed. It logs in the idea.log WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen. And dumps the thread:

AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
java.lang.Thread.State: RUNNABLE
(in native)
at java.base@17.0.5/sun.nio.ch.Net.poll(Native Method)
at java.base@17.0.5/sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
at java.base@17.0.5/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:285)
at java.base@17.0.5/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
at java.base@17.0.5/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
at java.base@17.0.5/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
at java.base@17.0.5/java.net.Socket$SocketInputStream.read(Socket.java:966)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
```

This looks like there is an error during read the Response Header but the http connection got a result

**Comment by MCMicS** [comment]
Do you have any proxy configured on system or in IntelliJ?

**Comment by lemon4github** [comment]
yes I'm working in a company framework with an proxy configuration in Intellij but the configured Jenkins URL is configured in the no proxy for list.

**Comment by MCMicS** [comment]
I hope I found the error. I currently fix it and try to give you a additional eap to test

**Comment by MCMicS** [comment]
Could you please try following: https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/263516

I not used the Proxy Exception list so your calls was all routed through your proxy and this will lead into this error.

**Comment by lemon4github** [comment]
https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/eap/263516 is working in 2022.3. The bug is fixed. Goog job !!!

**Comment by MCMicS** [comment]
Thanks for test

**Comment by MCMicS** [comment]
released with [0.13.16](https://plugins.jetbrains.com/plugin/6110-jenkins-control/versions/stable/277685)
